baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'
theme = "wkt"
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

name = "wkt"
license = "MIT"
licenselink = ""
description = "Minimal academic Hugo theme with sidebar profile."
homepage = ""
tags = ["minimal", "academic", "blog"]
features = ["sidebar profile", "tags", "categories", "toc", "syntax highlight"]
min_version = "0.120.0"

[author]
  name = "wkt"
